# Dependency: XP 5.9.1

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - wget 'http://xp-framework.net/setup/5.9.9' -O - | php -- -d . -f

script:
  - ./unittest src/test/config/*ini
