# This provides an initial configuration to
# test xp-language on http://travis-ci.org/

language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - wget 'http://xp-framework.net/setup/5.9.0' -O - | php -- -d .

script:
  - cd compiler && ./unittest src/test/resources/*ini